name: Code Style

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  artifact-metadata: write

jobs:
    check:
        uses: TheDragonCode/.github/.github/workflows/code-style.yml@main
